# Generated by Django 5.0.6 on 2024-05-26 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuroobi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tabyouin',
            fields=[
                ('tabyouinid', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('tabyouinmei', models.CharField(max_length=64)),
                ('abyouinaddres', models.CharField(max_length=64)),
                ('tabyouintel', models.CharField(max_length=13)),
                ('abyouinshihonkin', models.IntegerField()),
                ('kyukyu', models.IntegerField()),
            ],
        ),
    ]
