# Generated by Django 5.0.6 on 2024-06-19 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kuroobi', '0005_prescription'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Prescription',
            new_name='Treatment',
        ),
    ]
