# Generated by Django 5.0.6 on 2024-06-21 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuroobi', '0006_rename_prescription_treatment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabyouin',
            name='tabyouintel',
            field=models.CharField(max_length=15),
        ),
    ]
